### ISSUE TITLE
Create PR template

### ISSUE THREAD

**Issue by ericis** [ourchitecture/hello-cloud#61]
We will need the following:

- A new PR template file for new PRs using the [GitHub PR template guidance](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
- Place the file in the ".github/PULL_REQUEST_TEMPLATE/pull_request_template.md" directory
- Add content for the file using the example below
- Edit the [Contributor Guide](https://www.ourchitecture.io/hello-cloud/contribute/#a-working-program) under step 13 of "a working program" to describe that we use a PR template

## Example

```
## Hey, I just made a Pull Request!

<!-- Please describe what you added, and add a screenshot if possible.
     That makes it easier to understand the change so we can :shipit: faster. -->

#### :heavy_check_mark: Checklist

<!--- Please include the following in your Pull Request when applicable: -->

- [ ] You have read the [Contributor Guide](https://www.ourchitecture.io/hello-cloud/contribute/)
- [ ] Added or updated documentation
- [ ] Tests for new functionality and regression tests for bug fixes (not applicable for documentation-only changes)
- [ ] Screenshots attached (for UI changes) *For documentation, please run the documentation locally (e.g. `make start-docs`) and provide a screenshot of the changes. For code, consider a brief animated gif that demonstrates the changes of 5 seconds or less. ([ScreenToGif](https://www.screentogif.com/) is a tool that can help)
- [ ] Ideally, all your commit messages follow the [Conventional Commit format](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Ideally, all your commits have a `Signed-off-by` line in the message. ([more info](https://github.com/backstage/backstage/blob/master/CONTRIBUTING.md#developer-certificate-of-origin))
```

**Comment by ktSuW** [comment]
Hi @ericis , I am Su and a student. Could you assign this task to me? I would like to work on it.

Since it is a new template, I would like to ask you the following questions. 

- Should I add a section under main readme.md file called Contributing Templates
- Under it, I will write something about contributing guidelines and add a link to the new folder?
- Should I create a new folder called contributing_templates and add it under hello-cloud?

Thanks!
Su

**Comment by ktSuW** [comment]
Hi @ericis , After you review my #88 task and if it is all good, may I work on this task? 

I have a question. Is it a good practice to run make and docker for the changes I have made. If so, I will experiment with them. Thanks.

**Comment by ericis** [comment]
@ktSuW great questions. I've updated the issue with more details. They should help answer most of your questions.

I don't believe it will answer the question below, so here is a better explanation:

> Is it a good practice to run make and docker for the changes I have made.

Yes, for this project. Every effort is made to ensure consistency when executing code on different machines (e.g. your machine, my machine, the DevOps Continuous Integration pipeline that uses GitHub Actions workflow, etc.). In order to accomplish this, GNU `make` allows complicated commands with arguments as well as multi-line scripts to be defined as as a single "target" (e.g. `make start-docs`). While this might be possible with other tools and languages, like using NodeJS with `yarn start` or `npm start`, the "hello-cloud" project focuses on many languages and tools and GNU `make` has been around for decades and [is still actively used in open source](https://qspace.library.queensu.ca/bitstream/handle/1974/15767/Martin_Douglas_H_201704_PHD.pdf?sequence=3&isAllowed=y), even being used to build the Linux source code!

However, each machine may have different Operating Systems, "middleware" (OS packages and other software installed), and configuration with different versions of software installed. So, what works on one machine may not work on another. Developers joke about "works on my machine!" Placing specific versions of tools into a container with a specific Operating System version, specific middleware versions and specific configuration provides us with an ["immutable server"](https://martinfowler.com/bliki/ImmutableServer.html). This provides significant guarantees that when any person or machine executes a task, it will be done consistently when it uses containers.

**Comment by ktSuW** [comment]
Hi Ericis, THANKS a lot for your explanation and answering my questions. I really appreciate it.  I understand now. 
I will learn about docker and how to use make file for this task. I will give you updates as I progress along. Could you assign this task to me? 
I found this course on youtube. Since I am new to docker, I will do this course for this task. 
- https://www.youtube.com/watch?v=3c-iBn73dDE&ab_channel=TechWorldwithNana

Thanks again for your thorough explanation!

**Comment by ericis** [comment]
> For conventional commit message, could I add the highlighted items such as feat, fix, style, etc. as below?

That looks great! Can you put the examples in double quotes? I do worry a little that people will copy-paste the examples though, like "fix: a bug fix" instead of something more specific like "fix: nodejs docker build".

For step 13, the PR template will be automatically provided by GitHub when they create a PR, so no need to link to it. So, we might say "13. Submit a PR request back to this project. [Learn about creating a pull request.](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)"

> If you can wait until next weekend...

Yes, no worries. You're making fantastic progress.

**Comment by ktSuW** [comment]
Thanks @ericis! I will change as per your feedback. ☺

**Comment by ktSuW** [comment]
Hi @ericis , 

I have started exploring docker starting from today since have been a bit busy with my school work. 
I will learn more about docker images and how to containerize a web application before I start commencing on the task. I will give you update this weekend.

Thanks for your patience. 

![image](https://user-images.githubusercontent.com/46551151/146186992-b37c405d-9144-42c4-8abc-3b38604edead.png)

**Comment by ericis** [comment]
Awesome @ktSuW . Once you understand how to run `docker run hello-world` it might be possible to go to the "hello-cloud" project and simply run `make start-docs`.

I see you appear to be running "Git BASH" for Windows that is built on MINGW64... This does not ship with GNU `make`; although some 32-bit versions did. If you haven't already installed `make`, you can read about installing support for `make` to "Git BASH" here: https://gist.github.com/evanwill/0207876c3243bbb6863e65ec5dc3f058#make

Once you have `make` installed, you should now be able to run `make start-docs`.

**Comment by ktSuW** [comment]
Thanks for the tips @ericis !  😃 I see. I will do that.

**Comment by ktSuW** [comment]
Hi @ericis  ,  I have submitted the PR. I have tried to use `make start-docs` and get the following error. I tried to reading up stackoverflow posts to fix this issue. However, I was not able to. 

So I did this task like I have done for the previous task. 
Could I ask you a question about the use of make and docker? They might be very simple questions for you, but I still could not wrap my head around.

1. make start-docs - by running this command first before changing anything, it starts docker ( I have read the [makefile](https://github.com/ourchitecture/hello-cloud/blob/3f78b1b974f08b48cc82f370a19b72ea150185bd/makefile) to understand better. After running it, I can start changing in issue branch? Does it auto-test things?
2. To better understand the use of make in this project, I searched online and came across with this [article](https://nicwortel.nl/blog/2019/01/29/building-web-applications-with-make). Is there any other useful that you could share to help for beginner level? Thanks!

**Comment by ericis** [comment]
Thank you @ktSuW . Yes, it looks like you have a space in the path of your current directory.

In the "./makefile", can you add double quotes to the volume argument and retry?

Examples:

- Add double quotes changing this `-v $(shell pwd):/app \` into this `--volume "$(shell pwd)":/app \`
- Add double quotes changing this `--volume $(shell pwd):/app \` into this `--volume "$(shell pwd)":/app \`

**Comment by ktSuW** [comment]
Hi @ericis , Thanks for your explanation! I will try it.

**Comment by ericis** [comment]
Closing this. Thank you @ktSuW . Great work!
